"""create tables in DB

Revision ID: 11d87aa9f116
Revises: 
Create Date: 2023-04-27 20:32:59.286535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "11d87aa9f116"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("egn_or_bulstat", sa.String(length=13), nullable=False),
        sa.Column("email", sa.String(length=60), nullable=False),
        sa.Column("password", sa.String(length=250), nullable=False),
        sa.Column("phone", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("driving_experience", sa.String(length=2), nullable=False),
        sa.Column("create_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("employee", "customer", "admin", name="roletype"),
            nullable=False,
        ),
        sa.Column(
            "customer_type",
            sa.Enum("company", "individual", name="customertype"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("egn_or_bulstat"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.String(), nullable=False),
        sa.Column("policy_number", sa.String(length=18), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
        sa.UniqueConstraint("policy_number"),
    )
    op.create_table(
        "estates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type_estate",
            sa.Enum("apartment", "house", "house_floor", name="estatetype"),
            nullable=False,
        ),
        sa.Column("policy_number", sa.String(length=15), nullable=True),
        sa.Column("town", sa.String(length=25), nullable=False),
        sa.Column("address", sa.String(length=200), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("garage", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "payed", "accepted", "canceled", name="state"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "vehicles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type_vehicle",
            sa.Enum(
                "car",
                "truck",
                "truck_n1",
                "motorbike",
                "bus",
                "trail",
                name="vehicletype",
            ),
            nullable=False,
        ),
        sa.Column("policy_number", sa.String(length=18), nullable=True),
        sa.Column("plate_number", sa.String(length=8), nullable=False),
        sa.Column("talon_number", sa.String(length=10), nullable=False),
        sa.Column("power", sa.String(length=50), nullable=False),
        sa.Column("engine", sa.String(length=50), nullable=False),
        sa.Column("seats", sa.String(length=10), nullable=False),
        sa.Column("registration_address", sa.String(length=200), nullable=False),
        sa.Column("talon_photo", sa.String(length=255), nullable=False),
        sa.Column(
            "steering_wheel_position",
            sa.Enum("left", "right", name="steeringwheelposition"),
            nullable=False,
        ),
        sa.Column("usage", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "payed", "accepted", "canceled", name="state"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plate_number"),
        sa.UniqueConstraint("talon_number"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicles")
    op.drop_table("estates")
    op.drop_table("transactions")
    op.drop_table("customers")
    # ### end Alembic commands ###
