"""Add colunm colour in vehicles

Revision ID: b6c34ee4f013
Revises: c021fea10090
Create Date: 2023-04-27 20:35:41.977777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b6c34ee4f013"
down_revision = "c021fea10090"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("colour", sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicles", schema=None) as batch_op:
        batch_op.drop_column("colour")

    # ### end Alembic commands ###
