"""Add column for soft delete

Revision ID: c021fea10090
Revises: 11d87aa9f116
Create Date: 2023-04-27 20:34:41.164684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c021fea10090"
down_revision = "11d87aa9f116"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("estates", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_deleted", sa.Boolean(), nullable=False))

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_deleted", sa.Boolean(), nullable=False))

    with op.batch_alter_table("vehicles", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_deleted", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vehicles", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    with op.batch_alter_table("estates", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    # ### end Alembic commands ###
